/**
 * 生成文件检测——用于符号消歧时的降权排名。
 *
 * 当 "Send" 这样的查询在 protobuf 脚手架、测试 mock 和手写实现中匹配到
 * 17 个符号时，FTS 排序器往往会将生成的桩代码排在前面，因为它们的名称与
 * 实现的名称完全相同（在 cosmos-sdk 上经验证——见 project_go_multi_module_audit
 * 记忆）。生成的桩代码通常没有可追溯的函数体，导致智能体最终还是要读取源文件。
 *
 * 本工具是一个纯路径分类器，在消歧时（findSymbol / findAllSymbols /
 * synapse_search 格式化）被调用，而非硬性过滤——生成节点仍保留在图中且
 * 可达；只是当存在同名的真实实现时，它们会排到最后。
 *
 * 范围：仅后缀模式。大多数生成文件遵循 `<basename>.<tool>.<ext>` 命名
 * 约定（`.pb.go`、`_grpc.pb.go`、`.g.dart`、`_pb2.py`），这已覆盖
 * Go 审计中发现的几乎全部情况。未来可补充：在提取阶段扫描规范的
 * `// Code generated by` 文件头，以覆盖那些不遵循后缀约定的罕见文件。
 */

const GENERATED_PATTERNS: ReadonlyArray<RegExp> = [
  // Go — protobuf / gRPC / pulsar
  /\.pb\.go$/,
  /\.pulsar\.go$/,
  /_grpc\.pb\.go$/,
  // Go — mockgen 输出。默认生成 `mock_<src>.go`；许多项目
  // （cosmos-sdk 使用 `expected_*_mocks.go`）重命名为 `*_mock.go` /
  // `*_mocks.go`。同时匹配两种后缀可覆盖两种约定，
  // 且不会对手写源文件产生误判风险。
  /_mock\.go$/,
  /_mocks\.go$/,
  /^mock_[^/]+\.go$/,
  // TypeScript / JavaScript — 常见代码生成后缀（Apollo / GraphQL
  // codegen、Prisma、Hasura、ts-proto、gRPC-web、swagger-codegen）。
  /\.generated\.[jt]sx?$/,
  /\.gen\.[jt]sx?$/,
  /\.pb\.[jt]s$/,
  /_pb\.[jt]s$/,
  /_grpc_pb\.[jt]s$/,
  // 被压缩后内嵌到代码库中的打包产物（文档站、示例）。其
  // 单字母符号使基于名称的边成为纯噪声。
  /\.min\.m?js$/,
  // Python — protobuf / gRPC / openapi-codegen
  /_pb2(_grpc)?\.py$/,
  /_pb2\.pyi$/,
  // C++ — protobuf
  /\.pb\.(cc|h)$/,
  // C# — protobuf / gRPC（protoc-gen-csharp 将输出放在 obj/ 下，但
  // 许多项目也会提交 *.g.cs 和 *Grpc.cs 同级文件）
  /\.g\.cs$/,
  /Grpc\.cs$/,
  // Java — protobuf / gRPC：protoc-gen-java 生成 `*OuterClass.java`，
  // protoc-gen-grpc-java 生成 `*Grpc.java`。XxxImplBase 抽象类
  // 位于 Xxx*Grpc.java 内部。
  /OuterClass\.java$/,
  /Grpc\.java$/,
  // Swift — protobuf
  /\.pb\.swift$/,
  // Dart — build_runner / freezed / json_serializable / chopper
  /\.g\.dart$/,
  /\.freezed\.dart$/,
  /\.pb\.dart$/,
  /\.pbgrpc\.dart$/,
  /\.chopper\.dart$/,
  // Rust — 常见 build.rs OUT_DIR 输出通常在源码树之外，
  // 但树内生成文件常使用 `*.generated.rs`。
  /\.generated\.rs$/,
];

/**
 * 根据文件名判断 `filePath` 是否为工具生成的源文件。
 * 仅基于路径——不读取文件内容。返回结果是消歧时的相关性提示，而非确定性判断。
 */
export function isGeneratedFile(filePath: string): boolean {
  return GENERATED_PATTERNS.some((p) => p.test(filePath));
}
